<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>_10xdevs.Api</RootNamespace>
		<Version>1.0.0-rc.1</Version>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
	  <UserSecretsId>6bfa8b66-6a58-4b80-b07f-860177abcab9</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" Version="12.4.1" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.22">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\10xdevs.Application\10xdevs.Application.csproj" />
		<ProjectReference Include="..\10xdevs.Infrastructure\10xdevs.Infrastructure.csproj" />
	</ItemGroup>

</Project>
