// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _10xdevs.Infrastructure.Data;

#nullable disable

namespace _10xdevs.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_10xdevs.Domain.Entities.Flashcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("SRSEaseFactor")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasDefaultValue(2.5m);

                    b.Property<int?>("SRSInterval")
                        .HasColumnType("int");

                    b.Property<int?>("SRSLastGrade")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SRSNextRepetitionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SRSRepetitions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SRSNextRepetitionDate")
                        .HasDatabaseName("IX_Flashcards_SRSNextRepetitionDate");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Flashcards_UserId");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_Flashcards_UserId_Status");

                    b.ToTable("Flashcards", null, t =>
                        {
                            t.HasCheckConstraint("CK_Flashcards_SRSLastGrade", "[SRSLastGrade] IS NULL OR ([SRSLastGrade] >= 0 AND [SRSLastGrade] <= 5)");

                            t.HasCheckConstraint("CK_Flashcards_Source", "[Source] IN (0, 1)");

                            t.HasCheckConstraint("CK_Flashcards_Status", "[Status] IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("_10xdevs.Domain.Entities.FlashcardGenerationEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcceptedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("CandidatesCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EditedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_FlashcardGenerationEvents_UserId");

                    b.ToTable("FlashcardGenerationEvents", (string)null);
                });

            modelBuilder.Entity("_10xdevs.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("_10xdevs.Domain.Entities.Flashcard", b =>
                {
                    b.HasOne("_10xdevs.Domain.Entities.User", "User")
                        .WithMany("Flashcards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Flashcards_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_10xdevs.Domain.Entities.FlashcardGenerationEvent", b =>
                {
                    b.HasOne("_10xdevs.Domain.Entities.User", "User")
                        .WithMany("FlashcardGenerationEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FlashcardGenerationEvents_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_10xdevs.Domain.Entities.User", b =>
                {
                    b.Navigation("FlashcardGenerationEvents");

                    b.Navigation("Flashcards");
                });
#pragma warning restore 612, 618
        }
    }
}
